#!/usr/bin/env python3
"""One-time script to convert swe_firms_data.json from a list of company
names to the object format expected by scraper.py, and to seed website URLs
for well-known companies.
 
Input format (before):  ["OpenAI", "Netflix", ...]
Output format (after):  [{"name": "OpenAI", "website": "https://openai.com", "careerUrl": null}, ...]
"""
import json
 
WEBSITE_MAP = {
    "OpenAI": "https://openai.com",
    "Anthropic": "https://www.anthropic.com",
    "Netflix": "https://www.netflix.com",
    "Airbnb": "https://www.airbnb.com",
    "Snowflake": "https://www.snowflake.com",
    "Coinbase": "https://www.coinbase.com",
    "Instacart": "https://www.instacart.com",
    "Roblox": "https://www.roblox.com",
    "Waymo": "https://waymo.com",
    "Discord": "https://discord.com",
    "Brex": "https://www.brex.com",
    "AppLovin": "https://www.applovin.com",
    "Jane Street": "https://www.janestreet.com",
    "Grammarly": "https://www.grammarly.com",
    "Facebook": "https://www.metacareers.com",
    "Amplitude": "https://amplitude.com",
    "Two Sigma": "https://www.twosigma.com",
    "Airtable": "https://airtable.com",
    "Credit Karma": "https://www.creditkarma.com",
    "DoorDash": "https://www.doordash.com",
    "Thumbtack": "https://www.thumbtack.com",
    "Chime": "https://www.chime.com",
    "Plaid": "https://plaid.com",
    "Samsara": "https://www.samsara.com",
    "Notion": "https://www.notion.so",
    "Broadcom": "https://www.broadcom.com",
    "Dropbox": "https://www.dropbox.com",
    "Apple": "https://www.apple.com",
    "Confluent": "https://www.confluent.io",
    "Lyft": "https://www.lyft.com",
    "ByteDance": "https://www.bytedance.com",
    "Opendoor": "https://www.opendoor.com",
    "Google": "https://www.google.com",
    "Etsy": "https://www.etsy.com",
    "Reddit": "https://www.reddit.com",
    "Affirm": "https://www.affirm.com",
    "Robinhood": "https://robinhood.com",
    "Pure Storage": "https://www.purestorage.com",
    "Palo Alto Networks": "https://www.paloaltonetworks.com",
    "LinkedIn": "https://www.linkedin.com",
    "Figma": "https://www.figma.com",
    "Pinterest": "https://www.pinterest.com",
    "UiPath": "https://www.uipath.com",
    "Braze": "https://www.braze.com",
    "Fastly": "https://www.fastly.com",
    "Stripe": "https://stripe.com",
    "Slack": "https://slack.com",
    "DRW": "https://drw.com",
    "Optiver": "https://optiver.com",
    "Gusto": "https://gusto.com",
    "MongoDB": "https://www.mongodb.com",
    "Twilio": "https://www.twilio.com",
    "Spotify": "https://www.spotify.com",
    "Klaviyo": "https://www.klaviyo.com",
    "HubSpot": "https://www.hubspot.com",
    "Mixpanel": "https://mixpanel.com",
    "eBay": "https://www.ebay.com",
    "Salesforce": "https://www.salesforce.com",
    "Asana": "https://asana.com",
    "Databricks": "https://www.databricks.com",
    "HashiCorp": "https://www.hashicorp.com",
    "PagerDuty": "https://www.pagerduty.com",
    "VMware": "https://www.vmware.com",
    "Datadog": "https://www.datadoghq.com",
    "PayPal": "https://www.paypal.com",
    "Rivian": "https://rivian.com",
    "NVIDIA": "https://www.nvidia.com",
    "Okta": "https://www.okta.com",
    "CrowdStrike": "https://www.crowdstrike.com",
    "GitHub": "https://github.com",
    "Cisco": "https://www.cisco.com",
    "SoFi": "https://www.sofi.com",
    "Amazon": "https://www.amazon.com",
    "Twitch": "https://www.twitch.tv",
    "Verkada": "https://www.verkada.com",
    "Fanatics": "https://www.fanatics.com",
    "Cloudera": "https://www.cloudera.com",
    "Splunk": "https://www.splunk.com",
    "Zscaler": "https://www.zscaler.com",
    "Squarespace": "https://www.squarespace.com",
    "SeatGeek": "https://seatgeek.com",
    "Walmart": "https://www.walmart.com",
    "Cockroach Labs": "https://www.cockroachlabs.com",
    "Peloton": "https://www.onepeloton.com",
    "Niantic": "https://nianticlabs.com",
    "Oracle": "https://www.oracle.com",
    "Electronic Arts": "https://www.ea.com",
    "Cloudflare": "https://www.cloudflare.com",
    "Twitter": "https://twitter.com",
    "Disney": "https://www.disney.com",
    "Indeed": "https://www.indeed.com",
    "ServiceTitan": "https://www.servicetitan.com",
    "Fivetran": "https://www.fivetran.com",
    "Dell Technologies": "https://www.dell.com",
    "MasterClass": "https://www.masterclass.com",
    "Quora": "https://www.quora.com",
    "ServiceNow": "https://www.servicenow.com",
    "Palantir": "https://www.palantir.com",
    "Retool": "https://retool.com",
    "Qualtrics": "https://www.qualtrics.com",
    "Ramp": "https://ramp.com",
    "Microsoft": "https://www.microsoft.com",
    "Zapier": "https://zapier.com",
    "Chainalysis": "https://www.chainalysis.com",
    "Audible": "https://www.audible.com",
    "Workday": "https://www.workday.com",
    "Equinix": "https://www.equinix.com",
    "Yahoo": "https://www.yahoo.com",
    "Pandora": "https://www.pandora.com",
    "MSCI": "https://www.msci.com",
    "StockX": "https://stockx.com",
    "Vimeo": "https://vimeo.com",
    "Scale AI": "https://scale.com",
    "Qualcomm": "https://www.qualcomm.com",
    "Smartsheet": "https://www.smartsheet.com",
    "GoDaddy": "https://www.godaddy.com",
    "Duolingo": "https://www.duolingo.com",
    "Zendesk": "https://www.zendesk.com",
    "SAP": "https://www.sap.com",
    "Sentry": "https://sentry.io",
    "ZoomInfo": "https://www.zoominfo.com",
    "Webflow": "https://webflow.com",
    "DraftKings": "https://www.draftkings.com",
    "Chegg": "https://www.chegg.com",
    "GoodRx": "https://www.goodrx.com",
    "Wealthfront": "https://www.wealthfront.com",
    "Zynga": "https://www.zynga.com",
    "DigitalOcean": "https://www.digitalocean.com",
    "Citadel": "https://www.citadel.com",
    "Hudson River Trading": "https://www.hudsonrivertrading.com",
    "Jump Trading": "https://www.jumptrading.com",
    "Point72": "https://www.point72.com",
    "Bridgewater Associates": "https://www.bridgewater.com",
    "Arrowstreet Capital": "https://www.arrowstreetcapital.com",
    "Balyasny Asset Management": "https://www.bam.com",
    "Akuna Capital": "https://akunacapital.com",
    "ExodusPoint Capital Management": "https://www.exoduspoint.com",
    "Schonfeld": "https://www.schonfeld.com",
    "WorldQuant": "https://www.worldquant.com",
    "Interactive Brokers": "https://www.interactivebrokers.com",
    "Vercel": "https://vercel.com",
    "Anduril Industries": "https://www.anduril.com",
    "Mozilla": "https://www.mozilla.org",
    "Coupang": "https://www.coupang.jobs",
    "Rippling": "https://www.rippling.com",
    "Cruise": "https://www.getcruise.com",
    "Roku": "https://www.roku.com",
    "Chan Zuckerberg Initiative": "https://chanzuckerberg.com",
    "Clubhouse": "https://www.clubhouse.com",
    "Chai Research": "https://www.chai-research.com",
    "Vatic Investments": "https://www.vaticinvestments.com",
    "TGS Management": "https://www.tgsmc.com",
    "Radix": "https://www.radix-trading.com",
    "Radix Trading": "https://www.radix-trading.com",
    "OpenSea": "https://opensea.io",
    "CIT": "https://www.cit.com",
    "CloudKitchens": "https://www.cloudkitchens.com",
    "Old Mission": "https://www.oldmissioncapital.com",
    "Titan": "https://www.titan.com",
    "Chronosphere": "https://chronosphere.io",
    "Toyota Research Institute": "https://www.tri.global",
    "Hightouch": "https://hightouch.com",
    "Jane": "https://www.janeapp.com",
    "Lacework": "https://www.lacework.com",
    "StrivR": "https://www.strivr.com",
    "NewsBreak": "https://www.newsbreak.com",
    "StriveWorks": "https://www.striveworks.com",
    "Luminar Technologies": "https://www.luminartech.com",
    "Nuro": "https://www.nuro.ai",
    "Hallow": "https://hallow.com",
    "Polygon Technology": "https://polygon.technology",
    "Trumid": "https://www.trumid.com",
    "Five Rings": "https://fiveringsllc.com",
    "HBO": "https://www.hbo.com",
    "Drop": "https://www.joindrop.com",
    "Hertz": "https://www.hertz.com",
    "PonyAI": "https://pony.ai",
    "The Voleon Group": "https://voleon.com",
    "Tanium": "https://www.tanium.com",
    "Oscar Health": "https://www.hioscar.com",
    "Oscar": "https://www.hioscar.com",
    "Color": "https://www.color.com",
    "Hopper": "https://www.hopper.com",
    "Temporal Technologies": "https://temporal.io",
    "Albert": "https://albert.com",
    "ClickUp": "https://clickup.com",
    "Mux": "https://www.mux.com",
    "DocuSign": "https://www.docusign.com",
    "Latch": "https://www.latch.com",
    "Clear Street": "https://clearstreet.io",
    "CoinTracker": "https://www.cointracker.io",
    "Tinder": "https://tinder.com",
    "Kargo": "https://kargo.com",
    "Recharge": "https://rechargepayments.com",
    "Recharge Payments": "https://rechargepayments.com",
    "Seesaw": "https://seesaw.com",
    "Noom": "https://www.noom.com",
    "Embark Trucks": "https://embarktrucks.com",
    "StubHub": "https://www.stubhub.com",
    "Citizen": "https://citizen.com",
    "Imply": "https://imply.io",
    "Verily": "https://verily.com",
    "ClassDojo": "https://www.classdojo.com",
    "Flexport": "https://www.flexport.com",
    "XPeng Motors": "https://www.xpeng.com",
    "Pinwheel": "https://www.pinwheelapi.com",
    "InnoPeak Technology": "https://www.innopeaktech.com",
    "Convoy": "https://convoy.com",
    "Chicago Trading": "https://www.chicagotrading.com",
    "Alation": "https://www.alation.com",
    "Argo AI": "https://www.argo.ai",
    "AutoX": "https://www.autox.ai",
    "Marqeta": "https://www.marqeta.com",
    "Symbotic": "https://www.symbotic.com",
    "Woven Planet Group": "https://www.woven.toyota",
    "Paxos": "https://www.paxos.com",
    "Metapack": "https://www.metapack.com",
    "Anaplan": "https://www.anaplan.com",
    "Caesars Entertainment": "https://www.caesars.com",
    "CAE": "https://www.cae.com",
    "CAES": "https://caes.com",
    "Modern Treasury": "https://www.moderntreasury.com",
    "Maven Securities": "https://www.mavensecurities.com",
    "Datavant": "https://datavant.com",
    "Remitly": "https://www.remitly.com",
    "Omada Health": "https://www.omadahealth.com",
    "BlackLine": "https://www.blackline.com",
    "Chainlink Labs": "https://chainlinklabs.com",
    "Nextdoor": "https://nextdoor.com",
    "TRM Labs": "https://www.trmlabs.com",
    "Haven Life": "https://havenlife.com",
    "Motional": "https://motional.com",
    "Attentive": "https://www.attentive.com",
    "Upstart": "https://www.upstart.com",
    "Sumo Logic": "https://www.sumologic.com",
    "Oportun": "https://www.oportun.com",
    "Socure": "https://www.socure.com",
    "Patreon": "https://www.patreon.com",
    "Mysten Labs": "https://mystenlabs.com",
    "FalconX": "https://www.falconx.io",
    "Protocol Labs": "https://protocol.ai",
    "Neuralink": "https://neuralink.com",
    "Proto": "https://www.proto.io",
    "SnapDocs": "https://snapdocs.com",
    "Bill.com": "https://www.bill.com",
    "Instabase": "https://instabase.com",
    "Medable": "https://www.medable.com",
    "Lithic": "https://lithic.com",
    "Weights and Biases": "https://wandb.ai",
    "One": "https://www.one.app",
    "One Concern": "https://www.oneconcern.com",
    "Ripple": "https://ripple.com",
    "Fly Zipline": "https://www.flyzipline.com",
    "Valon": "https://www.valon.com",
    "Verition Fund Management": "https://www.verition.com",
    "FuboTV": "https://www.fubo.tv",
    "Redfin": "https://www.redfin.com",
    "QuantLab": "https://www.quantlab.com",
    "Sage Intacct": "https://www.sage.com/en-us/sage-business-cloud/intacct/",
    "Ava Labs": "https://www.avalabs.org",
    "Afresh": "https://www.afresh.com",
    "Stitch Fix": "https://www.stitchfix.com",
    "ThredUp": "https://www.thredup.com",
    "Abnormal Security": "https://abnormalsecurity.com",
    "ActBlue": "https://www.actblue.com",
    "Grubhub": "https://www.grubhub.com",
    "LivePerson": "https://www.liveperson.com",
    "Sysdig": "https://sysdig.com",
    "The Trade Desk": "https://www.thetradedesk.com",
    "NYDIG": "https://nydig.com",
    "Riot Games": "https://www.riotgames.com",
    "Tableau Software": "https://www.tableau.com",
    "Zillow": "https://www.zillow.com",
    "PercipientAI": "https://percipient.ai",
    "Faraday Future": "https://www.ff.com",
    "CarGurus": "https://www.cargurus.com",
    "LendingClub": "https://www.lendingclub.com",
    "TripActions": "https://navan.com",
    "Lyra Health": "https://www.lyrahealth.com",
    "MomentiveAI": "https://www.momentive.ai",
    "CaptivateIQ": "https://www.captivateiq.com",
    "Amazon Conservation Team": "https://www.amazonteam.org",
    "Blend": "https://blend.com",
    "WePay": "https://go.wepay.com",
    "Tonal": "https://www.tonal.com",
    "Kodiak Robotics": "https://kodiak.ai",
    "HAP Capital": "https://www.hapcapital.com",
    "Exabeam": "https://www.exabeam.com",
    "EliseAI": "https://www.eliseai.com",
    "Outschool": "https://outschool.com",
    "NerdWallet": "https://www.nerdwallet.com",
    "Tubi": "https://tubitv.com",
    "SiriusXM": "https://www.siriusxm.com",
    "BlueOwl": "https://www.blueowl.com",
    "Life360": "https://www.life360.com",
    "Stytch": "https://stytch.com",
    "DNAnexus": "https://www.dnanexus.com",
    "Haven Technologies": "https://www.haventechnologies.com",
    "HighNote": "https://highnote.com",
    "Heap": "https://heap.io",
    "OpenTable": "https://www.opentable.com",
    "Devoted Health": "https://www.devoted.com",
    "23andMe": "https://www.23andme.com",
    "Udemy": "https://www.udemy.com",
    "Huntress": "https://www.huntress.com",
    "CloudTrucks": "https://www.cloudtrucks.com",
    "Vanta": "https://www.vanta.com",
    "Procore Technologies": "https://www.procore.com",
    "Insitro": "https://insitro.com",
    "Benchling": "https://www.benchling.com",
    "Dfinity": "https://dfinity.org",
    "Iterable": "https://iterable.com",
    "Turo": "https://turo.com",
    "Kensho Technologies": "https://kensho.com",
    "Walmart Global Tech": "https://www.walmart.com",
    "Human Interest": "https://humaninterest.com",
    "Warner Bros. Discovery": "https://www.wbd.com",
    "Pie Insurance": "https://pieinsurance.com",
    "Altana AI": "https://altana.ai",
    "Endpoint": "https://www.endpoint.com",
    "Better": "https://better.com",
    "Better Mortgage": "https://better.com",
    "Glean": "https://www.glean.com",
    "ConsenSys": "https://consensys.io",
    "Aerospike": "https://aerospike.com",
    "Collectors": "https://www.collectors.com",
    "Versa Networks": "https://versa-networks.com",
    "Freenome": "https://www.freenome.com",
    "Doximity": "https://www.doximity.com",
    "New Relic": "https://newrelic.com",
    "Outreach": "https://www.outreach.io",
    "OfferUp": "https://offerup.com",
    "Stellar Health": "https://www.stellar.health",
    "Strava": "https://www.strava.com",
    "GoPuff": "https://gopuff.com",
    "GTS": "https://www.gtsx.com",
    "NI": "https://www.ni.com",
    "Sisu Data": "https://sisudata.com",
    "Ampere Computing": "https://amperecomputing.com",
    "CoreMont": "https://www.coremont.com",
    "Incredible Health": "https://www.incrediblehealth.com",
    "Arlo Smart Home": "https://www.arlo.com",
    "BetterUp": "https://www.betterup.com",
    "HeartFlow": "https://www.heartflow.com",
    "MetaMap": "https://metamap.com",
    "Anyscale": "https://www.anyscale.com",
    "Butterfly Network": "https://www.butterflynetwork.com",
    "SolarWinds": "https://www.solarwinds.com",
    "Guild Education": "https://www.guild.com",
    "PlayStation": "https://www.playstation.com",
    "Xilinx": "https://www.xilinx.com",
    "Glassdoor": "https://www.glassdoor.com",
    "Aspiration": "https://www.aspiration.com",
    "Brigit": "https://www.hellobrigit.com",
    "Bread Financial": "https://www.breadfinancial.com",
    "Twin": "https://twin.so",
    "Invitae": "https://www.invitae.com",
    "Firework": "https://firework.com",
    "IonQ": "https://ionq.com",
    "Juniper Square": "https://www.junipersquare.com",
    "Labelbox": "https://labelbox.com",
    "PacBio": "https://www.pacb.com",
    "TuSimple": "https://www.tusimple.com",
    "SoundHound": "https://www.soundhound.com",
    "Aviatrix": "https://aviatrix.com",
    "Ares Management": "https://www.aresmgmt.com",
    "AuditBoard": "https://www.auditboard.com",
    "Delphix": "https://www.delphix.com",
    "Hinge Health": "https://www.hingehealth.com",
    "Hive": "https://thehive.ai",
    "Sada": "https://sada.com",
    "Pocket Gems": "https://pocketgems.com",
    "Rivos": "https://rivosinc.com",
    "Voltus": "https://www.voltus.co",
    "Crunchbase": "https://www.crunchbase.com",
    "Hinge": "https://hinge.co",
    "Citrix": "https://www.citrix.com",
    "Covariant": "https://covariant.ai",
    "Divvy": "https://getdivvy.com",
    "Divvy Homes": "https://www.divvyhomes.com",
    "McKinsey": "https://www.mckinsey.com",
    "QuantumScape": "https://www.quantumscape.com",
    "Dragos": "https://www.dragos.com",
    "Spring Health": "https://www.springhealth.com",
    "Five9": "https://www.five9.com",
    "Capsule": "https://www.capsule.com",
    "Chief": "https://chief.com",
    "Collibra": "https://www.collibra.com",
    "DataRobot": "https://www.datarobot.com",
    "Applied Intuition": "https://www.appliedintuition.com",
    "Dolby Laboratories": "https://www.dolby.com",
    "OPPO": "https://www.oppo.com",
    "Untapped": "https://www.untapped.io",
    "Malwarebytes": "https://www.malwarebytes.com",
    "ZipRecruiter": "https://www.ziprecruiter.com",
    "Mojo": "https://www.mojo.com",
    "Netskope": "https://www.netskope.com",
    "Weedmaps": "https://weedmaps.com",
    "Pando": "https://www.pando.com",
    "Moveworks": "https://www.moveworks.com",
    "Panther Labs": "https://panther.com",
    "Saks Fifth Avenue": "https://www.saksfifthavenue.com",
    "Skydio": "https://www.skydio.com",
    "Sigma Computing": "https://www.sigmacomputing.com",
    "Stavvy": "https://www.stavvy.com",
    "Wistia": "https://wistia.com",
    "ExtraHop": "https://www.extrahop.com",
    "Vouch Insurance": "https://www.vouch.us",
    "WorkOS": "https://workos.com",
    "Duo Security": "https://duo.com",
    "Onfido": "https://onfido.com",
    "Alteryx": "https://www.alteryx.com",
    "Cribl": "https://cribl.io",
    "DoubleVerify": "https://doubleverify.com",
    "Mural": "https://www.mural.co",
    "Archer": "https://www.archer.com",
    "Calm": "https://www.calm.com",
    "Varo Bank": "https://www.varomoney.com",
    "Medallia": "https://www.medallia.com",
    "Axon": "https://www.axon.com",
    "Density": "https://www.density.io",
    "Planning Center": "https://www.planningcenter.com",
    "WeWork": "https://www.wework.com",
    "AeroVironment": "https://www.avinc.com",
    "C3 AI": "https://c3.ai",
    "Maven Clinic": "https://www.mavenclinic.com",
    "Flatiron Health": "https://flatiron.com",
    "NextRoll": "https://nextroll.com",
    "10x Genomics": "https://www.10xgenomics.com",
    "Edelman Financial Engines": "https://www.edelmanfinancialengines.com",
    "Humane": "https://humane.com",
    "Moloco": "https://www.moloco.com",
    "SecureFrame": "https://secureframe.com",
    "Wheels": "https://wheels.com",
    "Wheels Up": "https://wheelsup.com",
    "Edelman": "https://www.edelman.com",
    "Thirty Madison": "https://www.thirtymadison.com",
    "YugaByte": "https://www.yugabyte.com",
    "Envoy": "https://envoy.com",
    "Sibros": "https://www.sibros.tech",
    "Esper": "https://esper.io",
    "Honor": "https://www.joinhonor.com",
    "The New York Times Company": "https://www.nytco.com",
    "The New York Times": "https://www.nytimes.com",
    "CareRev": "https://www.carerev.com",
    "Justworks": "https://www.justworks.com",
    "Prosper Marketplace": "https://www.prosper.com",
    "Headway": "https://headway.co",
    "eHealth": "https://www.ehealthinsurance.com",
    "Mission": "https://www.missionlane.com",
    "Mission Lane": "https://www.missionlane.com",
    "Wisk": "https://wisk.aero",
    "ecoATM": "https://www.ecoatm.com",
    "BitGo": "https://www.bitgo.com",
    "Domino Data Lab": "https://www.dominodatalab.com",
    "Capital Group": "https://www.capitalgroup.com",
    "Dave": "https://dave.com",
    "SoloIO": "https://www.solo.io",
    "FieldWire": "https://www.fieldwire.com",
    "Salsify": "https://www.salsify.com",
    "Sojern": "https://www.sojern.com",
    "Fullstory": "https://www.fullstory.com",
    "Capita": "https://www.capita.com",
    "ForgeRock": "https://www.forgerock.com",
    "Notable Health": "https://www.notablehealth.com",
    "Unit": "https://www.unit.co",
    "Unit21": "https://www.unit21.ai",
    "Nota": "https://www.trustnota.com",
    "Nauto": "https://www.nauto.com",
    "MNTN": "https://mountain.com",
    "Zuora": "https://www.zuora.com",
    "MyVest": "https://www.myvest.com",
    "Split Software": "https://www.split.io",
    "SAP Concur": "https://www.concur.com",
    "Swirlds Labs": "https://swirldslabs.com",
    "Workrise": "https://www.workrise.com",
    "Magic Leap": "https://www.magicleap.com",
    "Olo": "https://www.olo.com",
    "Roche": "https://www.roche.com",
    "Qualia": "https://www.qualia.com",
    "Rally Health": "https://www.rallyhealth.com",
    "Realtor.com": "https://www.realtor.com",
    "Snorkel AI": "https://snorkel.ai",
    "Flyr Labs": "https://flyrlabs.com",
    "OverJet": "https://www.overjet.ai",
    "Loom": "https://www.loom.com",
    "Addepar": "https://addepar.com",
    "Certik": "https://www.certik.com",
    "EvGo": "https://www.evgo.com",
    "OKCoin": "https://www.okcoin.com",
    "OK": "https://www.okx.com",
    "TextNow": "https://www.textnow.com",
    "Quantum Metric": "https://www.quantummetric.com",
    "InVision": "https://www.invisionapp.com",
    "Highspot": "https://www.highspot.com",
    "Brightwheel": "https://mybrightwheel.com",
    "Illumio": "https://www.illumio.com",
    "Blink": "https://blinkhealth.com",
    "Blink Health": "https://blinkhealth.com",
    "Propel": "https://www.joinpropel.com",
}
 
 
# Direct career/ATS URLs. When present, scraper.py skips auto-discovery and
# (for recognised ATS hosts like Greenhouse/Lever/Ashby/SmartRecruiters/Workday)
# hits a structured JSON API — much higher precision than HTML scraping.
#
# Prefer ATS URLs (boards.greenhouse.io/{slug}, jobs.lever.co/{slug},
# jobs.ashbyhq.com/{slug}, {tenant}.wd{n}.myworkdayjobs.com/{board}) over
# company career pages where possible.
CAREER_URL_MAP = {
    # ── Greenhouse ───────────────────────────────────────────────────────
    "OpenAI": "https://job-boards.greenhouse.io/openai",
    "Anthropic": "https://job-boards.greenhouse.io/anthropic",
    "Figma": "https://boards.greenhouse.io/figma",
    "Ramp": "https://boards.greenhouse.io/ramp",
    "Brex": "https://boards.greenhouse.io/brex",
    "Airtable": "https://boards.greenhouse.io/airtable",
    "Scale AI": "https://boards.greenhouse.io/scaleai",
    "Discord": "https://boards.greenhouse.io/discord",
    "Samsara": "https://boards.greenhouse.io/samsara",
    "Retool": "https://boards.greenhouse.io/retool",
    "Vercel": "https://boards.greenhouse.io/vercel",
    "Webflow": "https://boards.greenhouse.io/webflow",
    "Coinbase": "https://boards.greenhouse.io/coinbase",
    "Robinhood": "https://boards.greenhouse.io/robinhood",
    "Plaid": "https://boards.greenhouse.io/plaid",
    "Chime": "https://boards.greenhouse.io/chime",
    "Affirm": "https://boards.greenhouse.io/affirm",
    "Asana": "https://boards.greenhouse.io/asana",
    "HashiCorp": "https://boards.greenhouse.io/hashicorp",
    "Databricks": "https://boards.greenhouse.io/databricks",
    "Reddit": "https://boards.greenhouse.io/reddit",
    "Dropbox": "https://boards.greenhouse.io/dropbox",
    "Instacart": "https://boards.greenhouse.io/instacart",
    "DoorDash": "https://boards.greenhouse.io/doordash",
    "Cloudflare": "https://boards.greenhouse.io/cloudflare",
    "Notion": "https://boards.greenhouse.io/notion",
    "Flexport": "https://boards.greenhouse.io/flexport",
    "Attentive": "https://boards.greenhouse.io/attentive",
    "Duolingo": "https://boards.greenhouse.io/duolingo",
    "Airbnb": "https://boards.greenhouse.io/airbnb",
    "Pinterest": "https://boards.greenhouse.io/pinterest",
    "Lyft": "https://boards.greenhouse.io/lyft2",
    "Confluent": "https://boards.greenhouse.io/confluent",
    "MongoDB": "https://boards.greenhouse.io/mongodb",
    "Cockroach Labs": "https://boards.greenhouse.io/cockroachlabs",
    "Roblox": "https://boards.greenhouse.io/roblox",
    "Datadog": "https://boards.greenhouse.io/datadog",
    "Snowflake": "https://boards.greenhouse.io/snowflake",
    "Grammarly": "https://boards.greenhouse.io/grammarly",
    "Stripe": "https://stripe.com/jobs/search",
    "Anduril Industries": "https://boards.greenhouse.io/anduril",
    "Mozilla": "https://boards.greenhouse.io/mozilla",
    "Rippling": "https://boards.greenhouse.io/rippling",
    "Glean": "https://boards.greenhouse.io/gleanwork",
    "Modern Treasury": "https://boards.greenhouse.io/moderntreasury",
    "Hightouch": "https://boards.greenhouse.io/hightouch",
    "Mixpanel": "https://boards.greenhouse.io/mixpanel",
    "Amplitude": "https://boards.greenhouse.io/amplitude",
    "Klaviyo": "https://boards.greenhouse.io/klaviyo",
    "PagerDuty": "https://boards.greenhouse.io/pagerduty",
    "Sentry": "https://sentry.io/careers/",
    "Patreon": "https://boards.greenhouse.io/patreon",
    "Nextdoor": "https://boards.greenhouse.io/nextdoor",
    "Remitly": "https://boards.greenhouse.io/remitly",
    "Gusto": "https://boards.greenhouse.io/gusto",
    "Zapier": "https://boards.greenhouse.io/zapier",
    "Crunchbase": "https://boards.greenhouse.io/crunchbase",
    "DigitalOcean": "https://boards.greenhouse.io/digitalocean",
    "Braze": "https://boards.greenhouse.io/braze",
    "Fastly": "https://boards.greenhouse.io/fastly",
    "Sysdig": "https://boards.greenhouse.io/sysdig",
    "Ava Labs": "https://boards.greenhouse.io/avalabs",
    "Mysten Labs": "https://boards.greenhouse.io/mystenlabs",
    "Chainalysis": "https://boards.greenhouse.io/chainalysis",
    "Lithic": "https://boards.greenhouse.io/lithic",
    "Clear Street": "https://boards.greenhouse.io/clearstreet",
    "Addepar": "https://boards.greenhouse.io/addepar",
    "Paxos": "https://boards.greenhouse.io/paxos",
    "Chainlink Labs": "https://boards.greenhouse.io/chainlinklabs",
    "TRM Labs": "https://boards.greenhouse.io/trmlabs",
    "Ripple": "https://boards.greenhouse.io/ripple",
    "Benchling": "https://boards.greenhouse.io/benchling",
    "Vanta": "https://boards.greenhouse.io/vanta",
    "Abnormal Security": "https://boards.greenhouse.io/abnormalsecurity",
    "CrowdStrike": "https://boards.greenhouse.io/crowdstrike",
    "Okta": "https://boards.greenhouse.io/okta",
 
    # ── Lever ────────────────────────────────────────────────────────────
    "Netflix": "https://jobs.netflix.com/jobs",
    "Palantir": "https://jobs.lever.co/palantir",
    "Fanatics": "https://jobs.lever.co/fanatics",
 
    # ── Ashby ────────────────────────────────────────────────────────────
    "Cruise": "https://jobs.ashbyhq.com/cruise",
 
    # ── SmartRecruiters ──────────────────────────────────────────────────
    "Square": "https://jobs.smartrecruiters.com/Square",
 
    # ── Workday ──────────────────────────────────────────────────────────
    "Salesforce": "https://salesforce.wd12.myworkdayjobs.com/External_Career_Site",
    "NVIDIA": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
    "Apple": "https://jobs.apple.com/en-us/search",
    "Workday": "https://workday.wd5.myworkdayjobs.com/Workday",
    "Broadcom": "https://broadcom.wd1.myworkdayjobs.com/External_Career",
    "ServiceNow": "https://servicenow.wd1.myworkdayjobs.com/ServiceNowCareers",
    "Cisco": "https://jobs.cisco.com/jobs/SearchJobs/",
    "VMware": "https://careers.vmware.com/main/jobs",
    "Oracle": "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/",
    "SAP": "https://jobs.sap.com/",
    "Walmart": "https://careers.walmart.com/",
    "Amazon": "https://www.amazon.jobs/en/",
    "Microsoft": "https://jobs.careers.microsoft.com/global/en/search",
    "Google": "https://www.google.com/about/careers/applications/",
    "LinkedIn": "https://careers.linkedin.com/jobs",
    "PayPal": "https://paypal.eightfold.ai/careers",
    "Intuit": "https://jobs.intuit.com/",
    "eBay": "https://careers.ebayinc.com/us/en/search-results",
    "Spotify": "https://www.lifeatspotify.com/jobs",
    "Zscaler": "https://zscaler.wd5.myworkdayjobs.com/External",
    "Palo Alto Networks": "https://jobs.paloaltonetworks.com/en/search-jobs",
    "GitHub": "https://github.com/about/careers",
    "Twitch": "https://www.twitch.tv/jobs/en/",
    "HubSpot": "https://www.hubspot.com/careers/jobs",
    "Indeed": "https://www.indeed.jobs/",
    "Electronic Arts": "https://ea.gr8people.com/jobs",
    "Riot Games": "https://www.riotgames.com/en/work-with-us/jobs",
    "Disney": "https://jobs.disneycareers.com/",
 
    # ── Direct careers pages (non-ATS, known-good) ──────────────────────
    "Jane Street": "https://www.janestreet.com/join-jane-street/open-roles/",
    "Two Sigma": "https://careers.twosigma.com/careers/OpenRoles",
    "Citadel": "https://www.citadel.com/careers/open-opportunities/",
    "Hudson River Trading": "https://www.hudsonrivertrading.com/careers/",
    "Jump Trading": "https://www.jumptrading.com/careers/",
    "DRW": "https://drw.com/work-at-drw/open-opportunities",
    "Optiver": "https://optiver.com/working-at-optiver/career-opportunities/",
    "Akuna Capital": "https://akunacapital.com/careers",
    "Point72": "https://careers.point72.com/",
    "Bridgewater Associates": "https://www.bridgewater.com/careers/open-positions",
    "Arrowstreet Capital": "https://www.arrowstreetcapital.com/careers/",
    "WorldQuant": "https://www.worldquant.com/career-listing/",
    "Balyasny Asset Management": "https://bambusdev.bamfunds.com/careers/",
    "ExodusPoint Capital Management": "https://www.exoduspoint.com/careers",
    "Schonfeld": "https://www.schonfeld.com/careers/",
    "Interactive Brokers": "https://www.interactivebrokers.com/en/general/about/careers.php",
    "Five Rings": "https://fiveringsllc.com/careers/",
    "Chicago Trading": "https://www.chicagotrading.com/careers/open-positions/",
    "Maven Securities": "https://www.mavensecurities.com/careers/",
    "QuantLab": "https://www.quantlab.com/careers",
    "Verition Fund Management": "https://www.verition.com/careers",
    "HAP Capital": "https://www.hapcapital.com/careers",
    "Old Mission": "https://www.oldmissioncapital.com/careers/",
    "The Voleon Group": "https://voleon.com/careers/",
    "Vatic Investments": "https://www.vaticinvestments.com/careers",
    "TGS Management": "https://www.tgsmc.com/careers",
    "Radix Trading": "https://www.radix-trading.com/open-positions/",
    "GTS": "https://www.gtsx.com/careers",
    "CoreMont": "https://www.coremont.com/careers",
    "Trumid": "https://www.trumid.com/careers/",
    "AppLovin": "https://www.applovin.com/careers/",
    "ByteDance": "https://jobs.bytedance.com/en/",
    "Meta": "https://www.metacareers.com/jobs",
    "Facebook": "https://www.metacareers.com/jobs",
}
 
 
def main():
    with open("swe_firms_data.json", "r", encoding="utf-8") as f:
        data = json.load(f)
 
    # Handle both formats: plain list of strings or already-converted objects.
    firms = []
    for entry in data:
        if isinstance(entry, str):
            name = entry
            existing = None
        elif isinstance(entry, dict):
            name = entry.get("name", "")
            existing = entry
        else:
            continue
        if not name:
            continue
 
        website = (existing or {}).get("website") or WEBSITE_MAP.get(name)
        career_url = (existing or {}).get("careerUrl") or CAREER_URL_MAP.get(name)
 
        firms.append({
            "name": name,
            "website": website,
            "careerUrl": career_url,
        })
 
    with open("swe_firms_data.json", "w", encoding="utf-8") as f:
        json.dump(firms, f, indent=2, ensure_ascii=False)
 
    seeded_site = sum(1 for f in firms if f["website"])
    seeded_career = sum(1 for f in firms if f["careerUrl"])
    print(
        f"Wrote {len(firms)} firms to swe_firms_data.json "
        f"({seeded_site} with website URLs, {seeded_career} with careerUrls)."
    )
 
 
if __name__ == "__main__":
    main()