#!/usr/bin/env python3
"""
One-time script to populate website URLs for PE firms in pe_firms_data.json.
The scraper needs at least a website field to discover career pages.
"""
import json
 
# Mapping of firm name -> website URL
# Sources: firm websites, SEC filings, industry databases
WEBSITE_MAP = {
    "Kohlberg Kravis Roberts": "https://www.kkr.com",
    "Harbourvest Partners": "https://www.harbourvest.com",
    "Thoma Bravo": "https://www.thomabravo.com",
    "Blackstone Management Partners": "https://www.blackstone.com",
    "CVC Advisers Jersey Limited": "https://www.cvc.com",
    "TPG Capital Advisors": "https://www.tpg.com",
    "Hellman & Friedman": "https://www.hfrp.com",
    "Silver Lake Technology Management": "https://www.silverlake.com",
    "Vista Equity Partners Management": "https://www.vistaequitypartners.com",
    "Global Infrastructure Management": "https://www.global-infra.com",
    "Warburg Pincus": "https://www.warburgpincus.com",
    "Insight Venture Partners": "https://www.insightpartners.com",
    "Advent International": "https://www.adventinternational.com",
    "Coatue Management": "https://www.coatue.com",
    "Stepstone Group": "https://www.stepstonegroup.com",
    "Pantheon": "https://www.pantheon.com",
    "Hamilton Lane": "https://www.hamiltonlane.com",
    "General Atlantic Service": "https://www.generalatlantic.com",
    "Clayton Dubilier & Rice": "https://www.cdr-inc.com",
    "Bain Capital Private Equity": "https://www.baincapital.com",
    "Brookfield Asset Management PIC Canada": "https://www.brookfield.com",
    "Leonard Green & Partners": "https://www.leonardgreen.com",
    "Tiger Global Management": "https://www.tigerglobal.com",
    "Blue OWL Gpsc Advisors": "https://www.blueowl.com",
    "EQT Fund Management S.A.R.L": "https://www.eqtgroup.com",
    "Lexington Partners": "https://www.lexingtonpartners.com",
    "BDT Capital Partners": "https://www.bdtmsd.com",
    "Strategic Partners Fund Solutions Advisors": "https://www.blackstone.com",
    "Sixth Street Advisers": "https://www.sixthstreet.com",
    "Goldman Sachs Private Equity": "https://www.goldmansachs.com",
    "NB Alternatives Advisers": "https://www.nb.com",
    "H.I.G. Capital": "https://www.higcapital.com",
    "Blackrock Capital Investment Advisors": "https://www.blackrock.com",
    "SB Investment Advisers US": "https://visionfund.com",
    "Hillhouse Investment Management": "https://www.hillhouseinvestment.com",
    "Hongshan Capital Advisors Limited": "https://www.hongshan.com",
    "Clearlake Capital Group": "https://www.clearlakecapital.com",
    "Adams Street Partners": "https://www.adamsstreetpartners.com",
    "Stone Point Capital": "https://www.stonepoint.com",
    "Platinum Equity Advisors": "https://www.platinumequity.com",
    "Ardian Investment UK Limited": "https://www.ardian.com",
    "I Squared Capital Advisors US": "https://www.isquaredcapital.com",
    "Ardian France": "https://www.ardian.com",
    "Francisco Partners": "https://www.franciscopartners.com",
    "Apax Partners": "https://www.apax.com",
    "HG": "https://www.hgcapital.com",
    "GTCR": "https://www.gtcr.com",
    "Veritas Capital Fund Management": "https://www.veritascapital.com",
    "BC Partners": "https://www.bcpartners.com",
    "Stonepeak": "https://www.stonepeakpartners.com",
    "Brookfield Renewable Energy Group": "https://www.brookfield.com",
    "Pathway Capital Management": "https://www.pathwaycapital.com",
    "Brookfield Asset Management PIC Adviser Private Equity": "https://www.brookfield.com",
    "Alpinvest US Holdings": "https://www.alpinvest.com",
    "Digitalbridge Investment Management": "https://www.digitalbridge.com",
    "Summit Partners": "https://www.summitpartners.com",
    "GCM Customized Fund Investment Group": "https://www.gcmgrosvenor.com",
    "Genstar Capital": "https://www.genstarcapital.com",
    "Nordic Capital": "https://www.nordiccapital.com",
    "Roark Capital Management": "https://www.roarkcapital.com",
    "Copenhagen Infrastructure Partners": "https://cipartners.dk",
    "TJC": "https://www.thejordancompany.com",
    "Blackrock Alternatives Management": "https://www.blackrock.com",
    "PSG Equity": "https://www.psgequity.com",
    "Macquarie Infrastructure & Real Assets Europe Limited": "https://www.macquarie.com",
    "Castlelake": "https://www.castlelake.com",
    "Bregal Investments": "https://www.bregal.com",
    "TDR Capital": "https://www.tdrcapital.com",
    "LGT Capital Partners Ireland Limited": "https://www.lgtcp.com",
    "Providence Equity Partners": "https://www.provequity.com",
    "D1 Capital Partners": "https://www.d1cap.com",
    "Dragoneer Investment Group": "https://www.dragoneer.com",
    "Berkshire Partners": "https://www.berkshirepartners.com",
    "New Mountain Capital": "https://www.newmountaincapital.com",
    "Macquarie Infrastructure Partners": "https://www.macquarie.com",
    "Carlyle Global Credit Investment Management": "https://www.carlyle.com",
    "Astorg Asset Management Sarl": "https://www.astorg.com",
    "KPS Capital Partners": "https://www.kpsfund.com",
    "American Securities": "https://www.american-securities.com",
    "Onex Partners Manager": "https://www.onex.com",
    "MBK Management": "https://www.mbkpartnersinc.com",
    "Harvest Partners": "https://www.harvestpartners.com",
    "Portfolio Advisors": "https://www.portad.com",
    "BTG Pactual Asset Management US": "https://www.btgpactual.com",
    "50 South Capital Advisors": "https://www.50southcapital.com",
    "TCV": "https://www.tcv.com",
    "Generation Investment Management": "https://www.generationim.com",
    "Quantum Capital Group": "https://www.quantumcapitalgroup.com",
    "SVB Capital": "https://www.svbcapital.com",
    "Stepstone Group Real Assets": "https://www.stepstonegroup.com",
    "Accel-KKR": "https://www.accel-kkr.com",
    "Partners Group AG": "https://www.partnersgroup.com",
    "Madison Dearborn Partners": "https://www.mdcp.com",
    "JAB Consumer Fund Management Sarl": "https://www.jabholco.com",
    "Audax Private Equity": "https://www.audaxprivateequity.com",
    "Kelso": "https://www.kelso.com",
    "Waterland Private Equity Investments": "https://www.waterland.nu",
    "Valor Equity Partners": "https://www.valorep.com",
    "Triton Investments Advisers": "https://www.triton-partners.com",
    "Alpha Wave Global": "https://www.alphawaveglobal.com",
    "GI Partners": "https://www.gipartners.com",
    "KSL Capital Partners": "https://www.kslcapital.com",
    "Morgan Stanley Infrastructure": "https://www.morganstanley.com",
    "CF Private Equity": "https://www.cfprivateequity.com",
    "Alpine Investors": "https://www.alpineinvestors.com",
    "Abry Partners II": "https://www.abry.com",
    "MS Capital Partners Adviser": "https://www.morganstanley.com",
    "Thrivent Financial FOR Lutherans": "https://www.thrivent.com",
    "TSG Consumer Partners": "https://www.tsgconsumer.com",
    "RCP Advisors 2": "https://www.rcpadvisors.com",
    "Westbridge Capital US Advisors": "https://www.westbridgecap.com",
    "Battery Management": "https://www.battery.com",
    "Siguler Guff Advisers": "https://www.sigulerguff.com",
    "Apogem Capital": "https://www.apogem.com",
    "K1 Investment Management": "https://www.k1capital.com",
    "AEA Qp Advisers": "https://www.aeainvestors.com",
    "Wcas Management": "https://www.wcas.com",
    "Boyu Capital Group Management": "https://www.boyucapital.com",
    "MIC Capital Management UK": "https://www.miccapital.com",
    "Peak XV Partners Operations": "https://www.peakxv.com",
    "ECP": "https://www.ecpartners.com",
    "Searchlight Capital Partners": "https://www.searchlightcap.com",
    "Great Hill Partners": "https://www.greathillpartners.com",
    "J.P. Morgan Private Investments": "https://www.jpmorgan.com",
    "3I Investments PLC": "https://www.3i.com",
    "Glendower Capital": "https://www.glendowercapital.com",
    "Partners Enterprise Capital": "https://www.partnersenterprise.com",
    "Riverside": "https://www.riversidecompany.com",
    "Whitehorse Liquidity Partners": "https://www.whitehorselp.com",
    "THL Managers VII": "https://www.thl.com",
    "Vitruvian Partners": "https://www.vitruvianpartners.com",
    "PAI Partners": "https://www.paipartners.com",
    "Blackstone Private Credit Strategies": "https://www.blackstone.com",
    "Arcline Investment Management": "https://www.arclineinvestment.com",
    "Kohlberg": "https://www.kohlberg.com",
    "Cinven Limited": "https://www.cinven.com",
    "SCS Capital Management": "https://www.scscapital.com",
    "Cinven Capital Management VII General Partner Limited": "https://www.cinven.com",
    "Oak Hill Capital Management": "https://www.oakhillcapital.com",
    "Riverstone Investment Group": "https://www.riverstonellc.com",
    "Truebridge Capital Partners": "https://www.truebridgecapital.com",
    "Carlyle Aviation PDP Management": "https://www.carlyle.com",
    "Sycamore Partners": "https://www.sycamorepartners.com",
    "Parthenon Capital Partners": "https://www.parthenoncapital.com",
    "EIG Management": "https://www.eigpartners.com",
    "Reverence Capital Partners": "https://www.reverencecapital.com",
    "Alpinvest Partners B.V.": "https://www.alpinvest.com",
    "Energy & Minerals Group": "https://www.emgtx.com",
    "STG Partners": "https://www.stgpartners.com",
    "Blackstone Strategic Capital Advisors": "https://www.blackstone.com",
    "Paradigm Operations": "https://www.yourparadigm.com",
    "Schroders Capital Management US": "https://www.schroderscapital.com",
    "Lime Rock": "https://www.lrpartners.com",
    "Digital Bridge Advisors": "https://www.digitalbridge.com",
    "OA Private Capital": "https://www.oaprivatecapital.com",
    "Hahn": "https://www.hahn.co.kr",
    "NGP": "https://www.ngpenergycapital.com",
    "Hall Capital Partners": "https://www.hallcapital.com",
    "Manulife Investment Management Private Markets US": "https://www.manulifeim.com",
    "Patria Finance Limited": "https://www.patria.com",
    "Cinven Capital Management VI General Partner Limited": "https://www.cinven.com",
    "OEP Capital Advisors": "https://www.oneequity.com",
    "Arctos Partners": "https://www.arctospartners.com",
    "Oakley Capital Manager Limited": "https://www.oakleycapital.com",
    "Asia Alternatives Management": "https://www.asiaalternatives.com",
    "Evergreen Investment Advisors": "https://www.evergreeninvestors.com",
    "Great Mountain Partners": "https://www.greatmountainpartners.com",
    "Arsenal Capital Management": "https://www.arsenalcapital.com",
    "Infravia Capital Partners": "https://www.infraviacapital.com",
    "One Rock Capital": "https://www.onerockcapital.com",
    "Certares Management": "https://www.certares.com",
    "Actis GP": "https://www.act.is",
    "Atalaya Capital Management": "https://www.atalayacap.com",
    "Bridgepoint Advisers Limited": "https://www.bridgepoint.eu",
    "Aquiline Management Holdings": "https://www.aquiline.com",
    "Golden Gate Capital": "https://www.goldengatecap.com",
    "Vistria Group": "https://www.thevistria.com",
    "Affinity Equity Partners Limited": "https://www.affinityequity.com",
    "Goldberg Lindsay": "https://www.goldberglindsay.com",
    "Gridiron Capital": "https://www.gridironcapital.com",
    "Grain Management": "https://www.grainmanagement.com",
    "Blackstone Multi-Asset Advisors": "https://www.blackstone.com",
    "Primavera Capital Management": "https://www.primaveracapital.com",
    "Pomona Capital": "https://www.pomonacapital.com",
    "Altaris": "https://www.altariscap.com",
    "Icon Infrastructure": "https://www.iconinfrastructure.com",
    "Gryphon Advisors": "https://www.gryphon-inv.com",
    "Wynnchurch Capital": "https://www.wynnchurch.com",
    "Sentinel Capital Partners": "https://www.sentinelpartners.com",
    "Arlington Capital Partners": "https://www.arlingtoncap.com",
    "Peak XV Partners I": "https://www.peakxv.com",
    "LS Power Equity Advisors": "https://www.lspower.com",
    "JMI Management": "https://www.jmi.com",
    "Greenbriar Equity Group": "https://www.greenbriarequity.com",
    "Inflexion Private Equity Partners": "https://www.inflexion.com",
    "VY Capital": "https://www.vycapital.com",
    "Blackstone Growth Advisors": "https://www.blackstone.com",
    "Crestview Partners": "https://www.crestview.com",
    "Wafra": "https://www.wafra.com",
    "Marlin Equity Partners": "https://www.marlinequity.com",
}
 
def main():
    with open("pe_firms_data.json", "r") as f:
        firms = json.load(f)
 
    updated = 0
    missing = []
 
    for firm in firms:
        name = firm["name"]
        if name in WEBSITE_MAP:
            firm["website"] = WEBSITE_MAP[name]
            updated += 1
        else:
            missing.append(name)
 
    with open("pe_firms_data.json", "w") as f:
        json.dump(firms, f, indent=2)
 
    print(f"Updated {updated}/{len(firms)} firms with website URLs")
    if missing:
        print(f"\nMissing URLs for {len(missing)} firms:")
        for name in missing:
            print(f"  - {name}")
 
if __name__ == "__main__":
    main()