#!/usr/bin/env python3
"""One-time script to populate website URLs for hedge fund firms."""
import json
 
WEBSITE_MAP = {
    "Millennium Management": "https://www.mlp.com",
    "Citadel Advisors": "https://www.citadel.com",
    "Qube Research & Technologies Limited": "https://www.qube-rt.com",
    "Capula Investment Management": "https://www.capula.com",
    "Symmetry Investments": "https://www.symmetryinvestments.com",
    "Balyasny Asset Management": "https://www.balyasny.com",
    "Pacific Investment Management": "https://www.pimco.com",
    "Rokos Capital Management": "https://www.rokoscapital.com",
    "Brevan Howard Capital Management": "https://www.brevanhoward.com",
    "Bridgewater Associates": "https://www.bridgewater.com",
    "Garda Capital Partners": "https://www.gardacapital.com",
    "Marshall Wace": "https://www.marshallwace.com",
    "Schonfeld Strategic Advisors": "https://www.schonfeld.com",
    "D. E. Shaw": "https://www.deshaw.com",
    "Mariner Investment Group": "https://www.marinerinvestmentgroup.com",
    "Alphadyne Asset Management": "https://www.alphadyne.com",
    "Exoduspoint Capital Management": "https://www.exoduspoint.com",
    "Verition Fund Management": "https://www.verition.com",
    "Oaktree Capital Management": "https://www.oaktreecapital.com",
    "Eisler Capital US": "https://www.eislercapital.com",
    "Two Sigma Investments": "https://www.twosigma.com",
    "Squarepoint OPS": "https://www.squarepoint-capital.com",
    "Two Sigma Advisers": "https://www.twosigma.com",
    "Fortress Investment Group": "https://www.fortress.com",
    "Blackrock Capital Management": "https://www.blackrock.com",
    "Renaissance Technologies": "https://www.rentec.com",
    "Cerberus Capital Management": "https://www.cerberus.com",
    "Arrowstreet Capital": "https://www.arrowstreetcapital.com",
    "Bracebridge Capital": "https://www.bracebridgecapital.com",
    "Elan Capital Management": "https://www.elancapitalmanagement.com",
    "TPG Angelo Gordon": "https://www.angelogordon.com",
    "Element Capital Management": "https://www.elementcapitalmanagement.com",
    "Capstone Investment Advisors": "https://www.capstoneco.com",
    "IFM Investors PTY": "https://www.ifminvestors.com",
    "Davidson Kempner Capital Management": "https://www.davidsonkempner.com",
    "AQR Capital Management": "https://www.aqr.com",
    "Tudor Investment": "https://www.tudorinvestmentcorp.com",
    "TA Associates": "https://www.ta.com",
    "Lighthouse Investment Partners": "https://www.lighthousepartners.com",
    "Farallon Capital Management": "https://www.faralloncapital.com",
    "Adage Capital Management": "https://www.adagecapital.com",
    "Kedalion Capital Management": "https://www.kedalioncapital.com",
    "Blackstone Infrastructure Advisors": "https://www.blackstone.com",
    "Centerbridge Partners": "https://www.centerbridge.com",
    "AHL Partners": "https://www.man.com",
    "Bayview Asset Management": "https://www.bayviewam.com",
    "Blackstone Tactical Opportunities Advisors": "https://www.blackstone.com",
    "Holocene Advisors": "https://www.holoceneadvisors.com",
    "Hudson BAY Capital Management": "https://www.hudsonbaycapital.com",
    "Ssga Funds Management": "https://www.ssga.com",
    "Tenaron Capital Management": "https://www.tenaroncapital.com",
    "Grosvenor Capital Management": "https://www.gcmgrosvenor.com",
    "Voloridge": "https://www.voloridge.com",
    "Paloma Partners Management": "https://www.palomapartners.com",
    "Walleye Capital": "https://www.walleyecapital.com",
    "Blackstone Alternative Solutions": "https://www.blackstone.com",
    "Silver Point Capital": "https://www.silverpointcapital.com",
    "Ares Capital Management": "https://www.aresmgmt.com",
    "Polar Asset Management Partners": "https://www.polaramp.com",
    "Select Equity Group": "https://www.selectequity.com",
    "White Oak Capital Management Consultants": "https://www.whiteoakcapital.com",
    "HHLR Advisors": "https://www.hhlr.com",
    "Caxton Associates": "https://www.caxton.com",
    "Haidar Capital Management": "https://www.haidarcapital.com",
    "Monarch": "https://www.monarchlp.com",
    "Baupost Group": "https://www.baupost.com",
    "Alkeon Capital Management": "https://www.alkeon.com",
    "Global Endowment Management": "https://www.globalendowment.com",
    "Lone Pine Capital": "https://www.lonepinecapital.com",
    "Marathon Asset Management": "https://www.marathonfund.com",
    "Alyeska Investment Group": "https://www.alyeskainvest.com",
    "Universa Investments": "https://www.universa.net",
    "Baker Brothers Investments": "https://www.bakerbros.com",
    "GC Advisors": "https://www.golubcapital.com",
    "Magnetar Financial": "https://www.magnetar.com",
    "Strategic Value Partners": "https://www.svpglobal.com",
    "Soroban Capital Partners": "https://www.sorobancap.com",
    "HBK Capital Management": "https://www.hbkcapital.com",
    "Meritage Group": "https://www.meritagegroup.com",
    "Capital Fund Management S.A.": "https://www.cfm.fr",
    "MIO Partners": "https://www.miopartners.com",
    "AB Carval Investors": "https://www.carval.com",
    "Systematica Investments Limited": "https://www.systematica.com",
    "Centiva Capital": "https://www.centivacapital.com",
    "Pershing Square Capital Management": "https://www.pershingsquareholdings.com",
    "Graham Capital Management": "https://www.grahamcapital.com",
    "III Capital Management": "https://www.iiicapitalmanagement.com",
    "Laurion Capital Management": "https://www.laurioncapital.com",
    "Linden Advisors": "https://www.lindenadvisors.com",
    "Investure": "https://www.investure.com",
    "Polar Capital": "https://www.polarcapital.co.uk",
    "Orbis Investment Management Limited": "https://www.orbis.com",
    "Cbre Investment Management": "https://www.cbreim.com",
    "Varde Management": "https://www.vfrde.com",
    "JJJ Capital Management": "https://www.jjjcapital.com",
    "Durable Capital Partners": "https://www.durablecapital.com",
    "Appaloosa": "https://www.appaloosamanagement.com",
    "Deerfield Management": "https://www.deerfield.com",
    "Magnitude Capital": "https://www.magnitudecapital.com",
    "Grantham Mayo VAN Otterloo": "https://www.gmo.com",
    "Permira Credit Limited": "https://www.permira.com",
    "Crestline Management": "https://www.crestline.com",
    "Woodline Partners": "https://www.woodlinepartners.com",
    "OQ Funds Management": "https://www.oqfm.com",
    "Himalaya Capital": "https://www.himalayacapital.com",
    "Ascension Investment Management": "https://www.ascensionim.com",
    "Waterfall Asset Management": "https://www.waterfallam.com",
    "Pharo Management": "https://www.pharomanagement.com",
    "Cevian Capital II Gp Limited": "https://www.ceviancapital.com",
    "Canyon Capital Advisors": "https://www.canyonpartners.com",
    "Effissimo Capital Management PTE": "https://www.effissimocapital.com",
    "Egerton Capital UK": "https://www.egertoncapital.com",
    "Mackay Shields": "https://www.mackayshields.com",
    "UBS Hedge Fund Solutions": "https://www.ubs.com",
    "D. E. Shaw Investment Management": "https://www.deshaw.com",
    "Kirkoswald Asset Management": "https://www.kirkoswald.com",
    "Beach Point Capital Management": "https://www.beachpointcapital.com",
    "Numeric Investors": "https://www.man.com",
    "SRS Investment Management": "https://www.srsinvestmentmanagement.com",
    "Compass Rose Asset Management": "https://www.compassrosefunds.com",
    "Saba Capital Management": "https://www.sabacapital.com",
    "Boothbay Fund Management": "https://www.boothbayfund.com",
    "Panagora Asset Management": "https://www.panagora.com",
    "Segantii Capital Management Limited": "https://www.segantii.com",
    "PDT Partners": "https://www.pdtpartners.com",
    "Wolver Hill Asset Management Asia Limited": "https://www.wolverhill.com",
    "LMR Partners": "https://www.lmrpartners.com",
    "Marshall Wace North America": "https://www.marshallwace.com",
    "Maverick Capital": "https://www.maverickcap.com",
    "UBS Oconnor": "https://www.ubs.com",
    "Vista Credit Partners": "https://www.vistaequitypartners.com",
    "Samlyn Capital": "https://www.samlyn.com",
    "Sona Asset Management US": "https://www.sonaassetmanagement.com",
    "Valueact Capital Management": "https://www.valueact.com",
    "Gerber/Taylor Management": "https://www.gerbertaylor.com",
    "Twinbeech Capital": "https://www.twinbeechcapital.com",
    "Highbridge Capital Management": "https://www.highbridgecap.com",
    "Pinnacle Asset Management": "https://www.pinnacle-am.com",
    "Redwood Capital Management": "https://www.rdwdcap.com",
    "Voleon Capital Management": "https://www.voleon.com",
    "Ellington Management Group": "https://www.ellington.com",
    "HG Vora Capital Management": "https://www.hgvora.com",
    "Corbin Capital Partners": "https://www.corbincapital.com",
    "One William Street Capital Management LP.": "https://www.onewilliamstreet.com",
    "Silver Creek Advisory Partners": "https://www.silvercreekcp.com",
    "Abrams Capital Management": "https://www.abramscapital.com",
    "Aristeia Capital": "https://www.aristeiacapital.com",
    "Crow Holdings Capital": "https://www.crowholdings.com",
    "Generation Investment Management US": "https://www.generationim.com",
    "Parametric Portfolio Associates": "https://www.parametricportfolio.com",
    "Junto Capital Management": "https://www.juntocapital.com",
    "Polymer Capital Management HK Limited": "https://www.polymercm.com",
    "Whale Rock Capital Management": "https://www.whalerockpoint.com",
    "Twin Tree Management": "https://www.twintreemanagement.com",
    "MAN Solutions Limited": "https://www.man.com",
    "MAN Solutions": "https://www.man.com",
    "Attestor Limited": "https://www.attestor.com",
    "Atairos Management": "https://www.atairos.com",
    "Windacre": "https://www.windacrepartnership.com",
    "Lombard Odier Asset Management USA": "https://www.lombardodier.com",
    "Parallax Volatility Advisers": "https://www.parallaxvolatility.com",
    "Loancore Capital Credit Advisor": "https://www.loancore.com",
    "Wolverine Asset Management": "https://www.wolam.com",
    "HSBC Global Asset Management Canada Limited": "https://www.hsbc.com",
    "Principal Real Estate": "https://www.principalam.com",
    "Marshall Wace Asia Limited": "https://www.marshallwace.com",
    "Avenue Capital Management II": "https://www.avenuecapital.com",
    "Braidwell": "https://www.braidwell.com",
    "Pentwater Capital Management": "https://www.pentwater.com",
    "Aspex Management HK Limited": "https://www.aspexmanagement.com",
    "First Sentier Investors": "https://www.firstsentierinvestors.com",
    "Steadfast Capital Management": "https://www.steadfastcap.com",
    "Tilden Park Capital Management": "https://www.tildenparkcm.com",
    "Trian Fund Management": "https://www.trianpartners.com",
    "MFN Partners Management": "https://www.mfnpartners.com",
    "Eminence Capital": "https://www.eminencecapital.com",
    "Christofferson Robb": "https://www.crcm.com",
    "Platinum Asset Management": "https://www.platinum.com.au",
    "Avanda Investment Management PTE": "https://www.avandaim.com",
    "Southpoint Capital Advisors": "https://www.southpointcapital.com",
    "Slate Path Capital": "https://www.slatepathcapital.com",
    "Bluecove Limited": "https://www.bluecove.com",
    "Zimmer Partners": "https://www.zimmerpartners.com",
    "Aquatic Capital Management": "https://www.aquaticcapital.com",
    "Weiss Asset Management": "https://www.weissasset.com",
    "Gemsstock": "https://www.gemsstock.com",
    "Jpmorgan Alternative Asset Management": "https://www.jpmorgan.com",
    "Jericho Capital Asset Management": "https://www.jerichocap.com",
    "Anchorage Capital Group": "https://www.anchoragecap.com",
    "VR Advisory Services": "https://www.vradvisory.com",
    "Overlook Investments": "https://www.overlookgroup.com",
    "Silver Rock Financial": "https://www.silverrockfinancial.com",
    "Nephila Capital": "https://www.nephila.com",
    "K2/D&S Management": "https://www.k2advisors.com",
    "Westport Capital Partners": "https://www.westportcp.com",
    "Candlestick Capital Management": "https://www.candlestickcap.com",
    "Towers Watson Investment Management": "https://www.wtwco.com",
    "Axium Infrastructure": "https://www.axiuminfra.com",
    "Glendon Capital Management": "https://www.glendoncapital.com",
    "BVF Partners": "https://www.bvfpartners.com",
    "Sylebra Capital": "https://www.sylebra.com",
    "Dorsal Capital Management": "https://www.dorsalcapital.com",
    "Paamco Prisma": "https://www.paamcoprisma.com",
    "Orchard Global Asset Management": "https://www.orchardglobal.com",
    "Bluespruce": "https://www.bluespruceinvestments.com",
    "Armistice Capital": "https://www.armisticecapital.com",
    "Tairen Capital Limited": "https://www.tairencapital.com",
    "MKP Capital Management": "https://www.mkpcapital.com",
    "Starboard Value": "https://www.starboardvalue.com",
    "Rock Springs Capital": "https://www.rockspringscapital.com",
    "Oasis Capital Partners Texas": "https://www.oasiscapitalpartners.com",
    "H/2 Capital Partners": "https://www.h2cap.com",
    "Amia Capital": "https://www.amiacapital.com",
    "Entrust Global Partners": "https://www.entrustglobal.com",
    "Foxhaven Asset Management": "https://www.foxhavenam.com",
    "Glenview Capital Management": "https://www.glenviewcapital.com",
    "Readystate Asset Management": "https://www.readystatecapital.com",
    "Route One Investment": "https://www.routeoneinvestment.com",
    "Senator Investment Group": "https://www.senatorlp.com",
    "GMT Capital": "https://www.gmtcapital.com",
    "Avidity Partners Management": "https://www.aviditypartners.com",
    "Alua Capital Management": "https://www.aluacapital.com",
    "Heitman Capital Management": "https://www.heitman.com",
    "Daemon Investment & Asset Management": "https://www.daemonim.com",
    "Blue OWL Real Estate Capital": "https://www.blueowl.com",
    "Janchor Partners": "https://www.janchorpartners.com",
    "SPX Capital Management": "https://www.spxcapital.com",
    "Deep Track Capital": "https://www.deeptrackcapital.com",
    "TPG Pep Advisors": "https://www.tpg.com",
    "Empyrean Capital Partners": "https://www.empyreancapital.com",
    "Caledonia US": "https://www.caledoniaus.com",
    "Stockbridge Investors": "https://www.stockbridgeinvestors.com",
    "Whitehaven Asset Management": "https://www.whitehavenam.com",
    "Avenue Europe International Management": "https://www.avenuecapital.com",
    "Naya Capital Management UK Limited": "https://www.nayacapital.com",
    "Pine River Capital Management": "https://www.pinerivercapital.com",
    "Altarock Partners": "https://www.altarockpartners.com",
    "Mantle Ridge": "https://www.mantleridge.com",
    "Conifer Management": "https://www.conifermanagement.com",
    "Bain Capital Public Equity": "https://www.baincapital.com",
    "DME Capital Management": "https://www.dmecapital.com",
    "Suvretta Capital Management": "https://www.suvretta.com",
    "Greenwoods Investments SG Pte.": "https://www.greenwoodsgroup.com",
    "Cadian Capital Management": "https://www.cadiancapital.com",
    "Hawk Ridge Capital Management": "https://www.hawkridgepartners.com",
    "KGH": "https://www.kghcapital.com",
    "Ninety One Luxembourg S.A.": "https://ninetyone.com",
    "Pillar Capital Management Limited": "https://www.pillarcap.com",
    "Camden Asset Management": "https://www.camdenasset.com",
    "Denham Capital Management": "https://www.denhamcapital.com",
    "Theleme Partners": "https://www.thelemepartners.com",
    "Evanston Capital Management": "https://www.evanstoncap.com",
    "Greenvale Capital": "https://www.greenvalecapital.com",
    "Finepoint Capital": "https://www.finepointcapital.com",
    "Anomaly Capital Management": "https://www.anomalycapital.com",
    "Cyrus Capital Partners": "https://www.cyruscapital.com",
    "Winton Capital Management": "https://www.winton.com",
    "Gates Capital Management": "https://www.gatescap.com",
    "3W Fund Management Limited": "https://www.3wfund.com",
    "Fundamental Advisors": "https://www.fundam.com",
    "Contour Asset Management": "https://www.contourasset.com",
    "Greywolf Capital Management": "https://www.greywolfcapital.com",
    "Blackstone Ireland Fund Management Limited": "https://www.blackstone.com",
    "Amansa Capital Pte.": "https://www.amansacapital.com",
    "Weiss Multi-Strategy Advisers": "https://www.weissmulti.com",
    "NUT Tree Capital Management": "https://www.nuttreecapital.com",
    "Palestra Capital Management": "https://www.palestracapital.com",
    "Boundary Creek Advisors": "https://www.boundarycreek.com",
    "Broad Peak Investment Advisers Pte.": "https://www.broadpeakim.com",
    "Trivest Advisors": "https://www.trivest.com",
    "Caspian Capital": "https://www.caspianlp.com",
    "Boulder Hill Capital Management": "https://www.boulderhillcapital.com",
    "Karya Capital Management": "https://www.karyacapital.com",
    "Kensico Capital Management": "https://www.kensicocapital.com",
    "140 Summer Partners": "https://www.140summerpartners.com",
    "Maplelane Capital": "https://www.maplelanecapital.com",
    "Skye Global Management": "https://www.skyeglobal.com",
    "Turtle Creek Asset Management": "https://www.turtlecreekam.com",
    "NWI Management": "https://www.nwim.com",
    "J. Goldman": "https://www.jgoldman.com",
    "Senvest Management": "https://www.senvest.com",
    "Crake Asset Management": "https://www.crakeam.com",
    "East Rock Capital": "https://www.eastrockcapital.com",
    "Sessa Capital": "https://www.sessacapital.com",
    "Valley Forge Capital Management": "https://www.valleyforgecm.com",
    "Cross Ocean Partners Management": "https://www.crossocean.com",
    "SPF Investment Management": "https://www.spfim.com",
    "My.Alpha": "https://www.myalpha.com",
    "Rubric Capital Management": "https://www.rubriccapital.com",
    "Camber Capital Management": "https://www.cambercap.com",
    "HMI Capital Management": "https://www.hmicapital.com",
    "Radcliffe Capital Management": "https://www.radcliffecapital.com",
    "Parvus Asset Management Europe Limited": "https://www.parvus.com",
    "Kite Lake Capital Management UK": "https://www.kitelake.com",
    "Tiff Investment Management": "https://www.tiff.org",
    "American Realty Advisors": "https://www.americanrealtyadvisors.com",
    "Rivulet Capital": "https://www.rivuletcapital.com",
    "Blackrock Asset Management North Asia Limited": "https://www.blackrock.com",
    "Sachem Head Capital Management": "https://www.sachemhead.com",
}
 
def main():
    with open("hedge_funds_data.json", "r") as f:
        firms = json.load(f)
 
    updated = 0
    missing = []
 
    for firm in firms:
        name = firm["name"]
        if name in WEBSITE_MAP:
            firm["website"] = WEBSITE_MAP[name]
            firm["careerUrl"] = None
            updated += 1
        else:
            firm["website"] = None
            firm["careerUrl"] = None
            missing.append(name)
 
    with open("hedge_funds_data.json", "w") as f:
        json.dump(firms, f, indent=2)
 
    print(f"Updated {updated}/{len(firms)} firms with website URLs")
    if missing:
        print(f"\nMissing URLs for {len(missing)} firms:")
        for name in missing:
            print(f"  - {name}")
 
if __name__ == "__main__":
    main()